export const STORE_TIMESTAMPS = "STORE_TIMESTAMPS";
export const DELETE_TIMESTAMPS = "DELETE_TIMESTAMPS";
export const STORE_MOVIES_DB = "STORE_MOVIES_DB";
export const DELETE_MOVIES_DB = "DELETE_MOVIES_DB";
