export const PENDING = "PENDING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const REMOVE_CURRENT_USER = "REMOVE_CURRENT_USER";
export const SET_AVATAR = "SET_AVATAR";
export const SET_USERS_PROFILE = "SET_USERS_PROFILE";
export const SET_CURRENT_PROFILE = "SET_CURRENT_PROFILE";
export const REMOVE_CURRENT_PROFILE = "REMOVE_CURRENT_PROFILE";
